# Generated by Django 2.2.10 on 2020-10-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routerdetails',
            old_name='status',
            new_name='is_deleted',
        ),
    ]
