# Generated by Django 2.2.10 on 2020-10-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20201027_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
